# Generated by Django 5.2.3 on 2025-06-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_360/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='public.product')),
            ],
        ),
    ]
