# Generated by Django 5.2.3 on 2025-06-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='The main title displayed on the homepage banner.', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='The smaller text displayed below the main title.')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
